🤖(rpm-spec) remove python3 binary
Should fix:
```
Error: Transaction test error:
  file /usr/lib/.build-id/21/79f0c994368adf0e9287396aa6382939ef5866 from install of electronim-0.0.87-0.fc37.x86_64 conflicts with file from package python3-3.11.0-1.fc37.x86_64
```

Signed-off-by: Marc Nuri <marc@marcnuri.com>